var ALIASES = {};
ALIASES['futures'] = {};
ALIASES['futures_channel'] = {};
ALIASES['futures_core'] = {};
ALIASES['futures_executor'] = {};
ALIASES['futures_io'] = {};
ALIASES['futures_sink'] = {};
ALIASES['futures_test'] = {};
ALIASES['futures_util'] = {};
